#!/usr/bin/env python3
"""
Log Viewer Utility for RealtimeVoiceChat

A simple utility to view, filter, and analyze log files generated by the server.
"""

import os
import sys
import argparse
from datetime import datetime
from pathlib import Path
import re

def get_log_files(logs_dir: str = "../logs") -> list:
    """Get all log files in the logs directory."""
    logs_path = Path(logs_dir)
    if not logs_path.exists():
        print(f"❌ Logs directory not found: {logs_path}")
        return []
    
    log_files = list(logs_path.glob("server_*.log"))
    return sorted(log_files, reverse=True)  # Most recent first

def tail_log_file(log_file: Path, lines: int = 50, follow: bool = False):
    """Tail a log file, similar to Unix tail command."""
    try:
        with open(log_file, 'r', encoding='utf-8') as f:
            # Get all lines and show the last 'lines' number
            all_lines = f.readlines()
            start_line = max(0, len(all_lines) - lines)
            
            print(f"📁 Showing last {lines} lines from: {log_file.name}")
            print("=" * 80)
            
            for line in all_lines[start_line:]:
                print(line.rstrip())
            
            if follow:
                print(f"🔄 Following {log_file.name} (Ctrl+C to stop)...")
                while True:
                    line = f.readline()
                    if line:
                        print(line.rstrip())
                    else:
                        import time
                        time.sleep(0.1)
                        
    except FileNotFoundError:
        print(f"❌ Log file not found: {log_file}")
    except KeyboardInterrupt:
        print("\n⏹️ Stopped following log file")
    except Exception as e:
        print(f"❌ Error reading log file: {e}")

def filter_log_file(log_file: Path, level: str = None, search: str = None, max_lines: int = None):
    """Filter log file by level and/or search term."""
    try:
        with open(log_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
            
        filtered_lines = []
        for line in lines:
            # Filter by level if specified
            if level and level.upper() not in line:
                continue
            
            # Filter by search term if specified
            if search and search.lower() not in line.lower():
                continue
            
            filtered_lines.append(line)
            
            # Limit output if max_lines specified
            if max_lines and len(filtered_lines) >= max_lines:
                break
        
        print(f"📁 Filtered results from: {log_file.name}")
        print(f"🔍 Filters: level={level}, search='{search}', max_lines={max_lines}")
        print("=" * 80)
        
        for line in filtered_lines:
            print(line.rstrip())
            
        print(f"\n📊 Found {len(filtered_lines)} matching lines")
        
    except FileNotFoundError:
        print(f"❌ Log file not found: {log_file}")
    except Exception as e:
        print(f"❌ Error filtering log file: {e}")

def show_log_stats(log_file: Path):
    """Show statistics about a log file."""
    try:
        with open(log_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        if not lines:
            print(f"📁 Log file is empty: {log_file.name}")
            return
        
        # Parse log entries
        log_entries = []
        for line in lines:
            # Try to parse timestamp and level
            match = re.match(r'(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})', line)
            if match:
                timestamp_str = match.group(1)
                try:
                    timestamp = datetime.strptime(timestamp_str, '%Y-%m-%d %H:%M:%S')
                    log_entries.append(timestamp)
                except ValueError:
                    continue
        
        if not log_entries:
            print(f"📁 No valid log entries found in: {log_file.name}")
            return
        
        # Calculate statistics
        total_lines = len(lines)
        valid_entries = len(log_entries)
        start_time = min(log_entries)
        end_time = max(log_entries)
        duration = end_time - start_time
        
        # Count log levels
        level_counts = {}
        for line in lines:
            for level in ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']:
                if level in line:
                    level_counts[level] = level_counts.get(level, 0) + 1
                    break
        
        print(f"📊 Statistics for: {log_file.name}")
        print("=" * 50)
        print(f"📄 Total lines: {total_lines}")
        print(f"✅ Valid log entries: {valid_entries}")
        print(f"⏰ Start time: {start_time}")
        print(f"⏰ End time: {end_time}")
        print(f"⏱️ Duration: {duration}")
        print(f"📈 Entries per minute: {valid_entries / max(duration.total_seconds() / 60, 1):.1f}")
        
        if level_counts:
            print("\n📊 Log levels:")
            for level, count in sorted(level_counts.items()):
                percentage = (count / valid_entries) * 100
                print(f"  {level}: {count} ({percentage:.1f}%)")
        
    except Exception as e:
        print(f"❌ Error analyzing log file: {e}")

def main():
    parser = argparse.ArgumentParser(description="Log Viewer for RealtimeVoiceChat")
    parser.add_argument("--logs-dir", default="../logs", help="Logs directory path")
    parser.add_argument("--list", action="store_true", help="List available log files")
    parser.add_argument("--file", help="Specific log file to view")
    parser.add_argument("--tail", type=int, default=50, help="Number of lines to show (default: 50)")
    parser.add_argument("--follow", action="store_true", help="Follow log file (like tail -f)")
    parser.add_argument("--level", help="Filter by log level (DEBUG, INFO, WARNING, ERROR)")
    parser.add_argument("--search", help="Search term to filter logs")
    parser.add_argument("--max-lines", type=int, help="Maximum lines to show when filtering")
    parser.add_argument("--stats", action="store_true", help="Show log file statistics")
    
    args = parser.parse_args()
    
    # List available log files
    if args.list:
        log_files = get_log_files(args.logs_dir)
        if not log_files:
            print("📁 No log files found")
            return
        
        print("📁 Available log files:")
        for log_file in log_files:
            size = log_file.stat().st_size
            mtime = datetime.fromtimestamp(log_file.stat().st_mtime)
            print(f"  {log_file.name} ({size} bytes, {mtime.strftime('%Y-%m-%d %H:%M:%S')})")
        return
    
    # Determine which log file to use
    if args.file:
        log_file = Path(args.logs_dir) / args.file
        if not log_file.exists():
            print(f"❌ Log file not found: {log_file}")
            return
    else:
        # Use most recent log file
        log_files = get_log_files(args.logs_dir)
        if not log_files:
            print("📁 No log files found")
            return
        log_file = log_files[0]
        print(f"📁 Using most recent log file: {log_file.name}")
    
    # Show statistics
    if args.stats:
        show_log_stats(log_file)
        return
    
    # Filter log file
    if args.level or args.search:
        filter_log_file(log_file, args.level, args.search, args.max_lines)
        return
    
    # Tail log file
    tail_log_file(log_file, args.tail, args.follow)

if __name__ == "__main__":
    main() 